"""extend_rate_per_sqft_to_3dp

Revision ID: 3bbc02343332
Revises: 010_property_other_expenses
Create Date: 2026-03-30 16:59:31.552073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbc02343332'
down_revision: Union[str, None] = '010_property_other_expenses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_deals', 'seller_rate_per_sqft',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
    op.alter_column('property_deals', 'buyer_rate_per_sqft',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_deals', 'buyer_rate_per_sqft',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('property_deals', 'seller_rate_per_sqft',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
